// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCKXqipuQ6Vw4mATUDwUaR7kg2xeb-L6k',
    appId: '1:243457884096:web:3a60bf42b59c7560ef1225',
    messagingSenderId: '243457884096',
    projectId: 'track-bank-expenses',
    authDomain: 'track-bank-expenses.firebaseapp.com',
    databaseURL: 'https://track-bank-expenses-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'track-bank-expenses.appspot.com',
    measurementId: 'G-5QHC5GSK5J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4ZZHDEmueYQAMIee8fw7Spkp7dZQ05WQ',
    appId: '1:243457884096:android:1da14ca2f471bdc2ef1225',
    messagingSenderId: '243457884096',
    projectId: 'track-bank-expenses',
    databaseURL: 'https://track-bank-expenses-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'track-bank-expenses.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOU_Wg9oQ0h7GyP-zPhLNZyzTiYmIWwMw',
    appId: '1:243457884096:ios:f1726722516c2108ef1225',
    messagingSenderId: '243457884096',
    projectId: 'track-bank-expenses',
    databaseURL: 'https://track-bank-expenses-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'track-bank-expenses.appspot.com',
    iosClientId: '243457884096-b8eap3gr93c8r2lk5i09f6emomo4td44.apps.googleusercontent.com',
    iosBundleId: 'com.transactions.tracker',
  );
}
